### ISSUE TITLE
Keep dollar-prefixed variables intact

### ISSUE THREAD

**Issue by jzaefferer** [sloppyio/sloppose#8]
sloppy.yml (and json) files support variables, prefixed with a dollar sign. Currently those get lost in the conversion:

input:
```
version: '3'
services:
  mysql:
    image: mysql:5.7.20
    environment:
      MYSQL_ROOT_PASSWORD: "$DBROOT"
```
expected output:
```
version: v1
project: wordpress
services:
  apps:
    mysql:
      env:
      - MYSQL_ROOT_PASSWORD: "$DBROOT"
      image: mysql:5.7.20
```
actual output:
```
version: v1
project: wordpress
services:
  apps:
    mysql:
      env:
      - MYSQL_ROOT_PASSWORD: ""
      image: mysql:5.7.20
```
Should keep the variable, instead it gets replaced with an empty string.
